### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by hepcat72** [hepcat72/flyMultiPlate#19]
Find out what Sudarshan and Ben would like in terms of license.

**Comment by hepcat72** [comment]
Hey @bpbratton,

Sudarshan and I have shot around the idea of formalizing a release of this code base.  I've been cleaning out vestigial code (yet to push).  Do you have a preference in terms of license?

Rob

**Comment by bpbratton** [comment]
I personally am a fan of BSD 3-clause. I’m not opposed BSD 2-clause but prefer to avoid GPL. I appreciate the notion of open source but copyleft protection feels too “preachy” to me. And that’s coming from a guy who personally loves preachers.


Ben Bratton


On Apr 28, 2017, at 12:45 PM, Robert Leach <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @bpbratton<https://github.com/bpbratton>,

Sudarshan and I have shot around the idea of formalizing a release of this code base. I've been cleaning out vestigial code (yet to push). Do you have a preference in terms of license?

Rob

**Comment by hepcat72** [comment]
Added a LICENSE file with the 3-Clause BSD.
