### ISSUE TITLE
Notify when script finishes or crashes

### ISSUE THREAD

**Issue by hepcat72** [hepcat72/flyMultiPlate#5]
Given the random crashing issue and the importance of catching crashes in a timely fashion, especially if not watching the run, it would be good to be notified when the script stops.  The following notifier function would be a good way to do it:

https://www.mathworks.com/matlabcentral/fileexchange/28733-notifier

**Comment by bpbratton** [comment]
I like notifier, but I seem to remember some oddities/security issues when trying to configure the sendmail preferences. I'd have to look back, but I think I ended up writing a wrapper to the system copy of  sendmail for notifications of remote jobs.

In the IoT era, it may be worth taking advantage of the twitter/matlab in the cloud api's for this type of thing as well.

Ben Bratton

On Feb 15, 2017, at 11:41 AM, Robert Leach <notifications@github.com<mailto:notifications@github.com>> wrote:


Given the random crashing issue and the importance of catching crashes in a timely fashion, especially if not watching the run, it would be good to be notified when the script stops. The following notifier function would be a good way to do it:

https://www.mathworks.com/matlabcentral/fileexchange/28733-notifier

**Comment by hepcat72** [comment]
This has become unnecessary since I seem to have resolved the crashing issue.
